build: 'off'
environment:
  matrix:
    - nodejs_version: '4'
    - nodejs_version: '6'
install:
  - ps: 'Install-Product node $env:nodejs_version x64'
  - npm install
test_script:
  - node --version
  - npm --version
  - npm cache clean
  - npm test
